build:
  image: docker:dind
  only:
    - tags
  before_script:
    - docker login
      --username gitlab-ci-token
      --password $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - TAG=$(echo $CI_COMMIT_REF_NAME | cut -d'.' -f 1)
    - docker build
      --force-rm
      --tag registry.gitlab.com/cgps/cog-uk/metadata.cog-uk.io:$TAG
      --build-arg REPO_USER=gitlab-ci-token 
      --build-arg REPO_TOKEN=${CI_JOB_TOKEN} 
      .
    - docker push
      registry.gitlab.com/cgps/cog-uk/metadata.cog-uk.io:$TAG
    - docker rmi
      --force
      registry.gitlab.com/cgps/cog-uk/metadata.cog-uk.io:$TAG
